ci: Check for nicely formatted JavaScript
according to javascript/.prettierrc

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -212,7 +212,7 @@ jobs:
           # dangling processes
           killall -9 creditcoin-node
 
-  java-script-lint:
+  javascript-lint:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
@@ -239,6 +239,43 @@ jobs:
 
           yarn lint
           yarn tsc
+
+          popd
+
+  javascript-prettier:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set-Up
+        run: |
+          sudo apt-get update
+          sudo apt install -y curl
+
+          # remove pre-installed packages
+          sudo apt remove npm nodejs
+
+          # Install Node.js 16.x from upstream b/c polkadot/jest can't work withh old versions
+          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+
+          sudo apt-get install -y nodejs
+          sudo npm install -g yarn
+
+      - name: Run tools
+        run: |
+          pushd javascript/
+
+          yarn install
+
+          yarn prettier --write .
+
+          git status
+          if [ -n "$(git status --short)" ]; then
+              git diff
+              echo "FAIL: JavaScript is not pretty!"
+              echo "HELP: Execute 'yarn prettier --write .' and commit the changes to fix this"
+              exit 1
+          fi
 
           popd
 
